### ISSUE TITLE
Tests of a non-babel dev server

### ISSUE THREAD

**Issue by peakwinter** [peakwinter/sylow#105]
Currently the dev server runs by babelizing the ES6 JavaScript to ES5, and exporting the contents to the `dist` subfolder before running. This renders debugging difficult.

We should: 

- ensure that we are only using code that is compatible with the latest version of the latest Node.js LTS (8.x),
- remove the babel components from the gulpfile (server only), and
- test everything.

**Comment by GuillaumeCz** [comment]
This issue was moved to GuillaumeCz/sylow#4
