### ISSUE TITLE
Code Climate maintainability rating

### ISSUE THREAD

**Issue by peakwinter** [peakwinter/sylow#106]
Currently the project has a Code Climate maintainability rating of D. Some of the reasons for this are silly (max limit of 250 lines per file, lolwut), but others may need addressing.

We should therefore:

- evaluate which suggestions are important to implement and which can be ignored,
- implement the important suggestions, and
- tell `.codeclimate.yml` to ignore the unimportant ones so our score is more accurate.

**Comment by GuillaumeCz** [comment]
This issue was moved to GuillaumeCz/sylow#3
